export interface SuperVariant {
    id: string,
    input_type: string,
    startup: string,
    active: string,
    recovery: string,
    advantage: string,
    immune_to: string,
    meter_used: string,
    super_id: string,
    gaurd: string,
    properties: string,
    special_notes: string,
    picture: {"url": string},
    created_at: string,
    updated_at: string,
}